### ISSUE TITLE
GitHub logo in footer is almost invisible

### ISSUE THREAD

**Issue by triallax** [00-Evan/00-Evan.github.io#5]
See this screenshot:
![screenshot](https://user-images.githubusercontent.com/32234660/188312702-e261186b-965a-42d5-877c-a9e8dc81fe28.png)
Perhaps the logo could be made white instead or something.

PS: Shattered Pixel Dungeon is a great game, thank you and the original developer. :)

**Comment by 00-Evan** [comment]
Had to manually override the CSS, but I do agree that the icon should be using github's dark mode colors. now using #F0F6FC as of commit 7f35e889cd2afbb1a67f2e20415af1571a9b3e60
